services:
  hugo:
    build:
      context: .
      args:
        HUGO_VERSION: ${HUGO_VERSION}
        GO_VERSION: ${GO_VERSION}
    volumes:
      - .:/site
    ports:
      - "1313:1313"
    command: hugo server --bind 0.0.0.0 --disableFastRender

  shell:
    build:
      context: .
      args:
        HUGO_VERSION: ${HUGO_VERSION}
        GO_VERSION: ${GO_VERSION}
    volumes:
      - .:/site
    stdin_open: true
    tty: true
    command: /bin/bash
